development:
  adapter: redis
  url: "redis://127.0.0.1:6379/0"

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:9483304f14984843b0fc8e7bbdcde6f1@viperfish.redistogo.com:11690/