default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host:     "192.168.99.100"
  port:     "5432"
  username: "postgres"
  database: "cancer_sns_development"

development:
  <<: *default

test:
  <<: *default

production:
  url: <%= ENV['DATABASE_URL'] %>