default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: cancer_sns_development

test:
  <<: *default
  database: cancer_sns_test

production:
  <<: *default
  database: cancer_sns_production
  # username: postgres
  # password: password