development:
  adapter: postgresql
  encoding: unicode
  database: cancer_sns_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cancer_sns_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
